version: '3.7'
services:
  server:
    build:
      context: docker
      dockerfile: Dockerfile
    container_name: 'fee_calculator'
    restart: 'on-failure'
    tty: true
    volumes:
      - .:/var/www
      - ./docker/vhost.conf:/etc/apache2/sites-enabled/000-default.conf
    ports:
      - '80:80'